version: '3.8'
services:
    nodefs:
        container_name: nodefs
        image: lunnaholy/nodefs
        restart: always
        volumes:
            - ./fs/storage:/usr/src/app/storage
        ports:
            - 9443:8080